name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**' 
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t jiasin/2025cloud:hello .

    - name: Push to DockerHub
      run: docker push jiasin/2025cloud:hello

